// Code generated by go-swagger; DO NOT EDIT.

package api

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// CartItemUpdateItemResponse cart item update item response
//
// swagger:model cartItem.UpdateItemResponse
type CartItemUpdateItemResponse struct {

	// desc
	Desc string `json:"desc,omitempty"`

	// name
	Name string `json:"name,omitempty"`

	// quantity
	Quantity int64 `json:"quantity,omitempty"`

	// sku
	Sku string `json:"sku,omitempty"`
}

// Validate validates this cart item update item response
func (m *CartItemUpdateItemResponse) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this cart item update item response based on context it is used
func (m *CartItemUpdateItemResponse) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *CartItemUpdateItemResponse) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *CartItemUpdateItemResponse) UnmarshalBinary(b []byte) error {
	var res CartItemUpdateItemResponse
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
