// Code generated by go-swagger; DO NOT EDIT.

package api

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// CategoryListCategoryResponse category list category response
//
// swagger:model category.ListCategoryResponse
type CategoryListCategoryResponse struct {

	// description
	Description string `json:"description,omitempty"`

	// name
	Name string `json:"name,omitempty"`
}

// Validate validates this category list category response
func (m *CategoryListCategoryResponse) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this category list category response based on context it is used
func (m *CategoryListCategoryResponse) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *CategoryListCategoryResponse) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *CategoryListCategoryResponse) UnmarshalBinary(b []byte) error {
	var res CategoryListCategoryResponse
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
