// Code generated by go-swagger; DO NOT EDIT.

package api

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"strconv"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// OrderCancelOrderResponse order cancel order response
//
// swagger:model order.CancelOrderResponse
type OrderCancelOrderResponse struct {

	// canceled at
	CanceledAt string `json:"canceled_at,omitempty"`

	// order Id
	OrderID string `json:"orderId,omitempty"`

	// order items
	OrderItems []*ProductGetProductResponse `json:"orderItems"`

	// total price
	TotalPrice float64 `json:"totalPrice,omitempty"`

	// total products
	TotalProducts int64 `json:"totalProducts,omitempty"`
}

// Validate validates this order cancel order response
func (m *OrderCancelOrderResponse) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateOrderItems(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *OrderCancelOrderResponse) validateOrderItems(formats strfmt.Registry) error {
	if swag.IsZero(m.OrderItems) { // not required
		return nil
	}

	for i := 0; i < len(m.OrderItems); i++ {
		if swag.IsZero(m.OrderItems[i]) { // not required
			continue
		}

		if m.OrderItems[i] != nil {
			if err := m.OrderItems[i].Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("orderItems" + "." + strconv.Itoa(i))
				} else if ce, ok := err.(*errors.CompositeError); ok {
					return ce.ValidateName("orderItems" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

// ContextValidate validate this order cancel order response based on the context it is used
func (m *OrderCancelOrderResponse) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := m.contextValidateOrderItems(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *OrderCancelOrderResponse) contextValidateOrderItems(ctx context.Context, formats strfmt.Registry) error {

	for i := 0; i < len(m.OrderItems); i++ {

		if m.OrderItems[i] != nil {
			if err := m.OrderItems[i].ContextValidate(ctx, formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("orderItems" + "." + strconv.Itoa(i))
				} else if ce, ok := err.(*errors.CompositeError); ok {
					return ce.ValidateName("orderItems" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

// MarshalBinary interface implementation
func (m *OrderCancelOrderResponse) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *OrderCancelOrderResponse) UnmarshalBinary(b []byte) error {
	var res OrderCancelOrderResponse
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
