// Code generated by go-swagger; DO NOT EDIT.

package api

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// ProductGetProductResponse product get product response
//
// swagger:model product.GetProductResponse
type ProductGetProductResponse struct {

	// category ID
	CategoryID string `json:"categoryID,omitempty"`

	// desc
	Desc string `json:"desc,omitempty"`

	// name
	Name string `json:"name,omitempty"`

	// price
	Price float64 `json:"price,omitempty"`

	// sku
	Sku string `json:"sku,omitempty"`

	// stock
	Stock int64 `json:"stock,omitempty"`
}

// Validate validates this product get product response
func (m *ProductGetProductResponse) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this product get product response based on context it is used
func (m *ProductGetProductResponse) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *ProductGetProductResponse) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *ProductGetProductResponse) UnmarshalBinary(b []byte) error {
	var res ProductGetProductResponse
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
