// Code generated by go-swagger; DO NOT EDIT.

package api

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// ProductCreateProductResponse product create product response
//
// swagger:model product.CreateProductResponse
type ProductCreateProductResponse struct {

	// ID
	ID int64 `json:"ID,omitempty"`

	// category ID
	CategoryID string `json:"categoryID,omitempty"`

	// created at
	CreatedAt string `json:"createdAt,omitempty"`

	// desc
	Desc string `json:"desc,omitempty"`

	// is active
	IsActive bool `json:"isActive,omitempty"`

	// name
	Name string `json:"name,omitempty"`

	// price
	Price float64 `json:"price,omitempty"`

	// sku
	Sku string `json:"sku,omitempty"`

	// stock
	Stock int64 `json:"stock,omitempty"`

	// updated at
	UpdatedAt string `json:"updatedAt,omitempty"`
}

// Validate validates this product create product response
func (m *ProductCreateProductResponse) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this product create product response based on context it is used
func (m *ProductCreateProductResponse) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *ProductCreateProductResponse) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *ProductCreateProductResponse) UnmarshalBinary(b []byte) error {
	var res ProductCreateProductResponse
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
