// Code generated by go-swagger; DO NOT EDIT.

package api

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// ProductUpdateProductRequest product update product request
//
// swagger:model product.UpdateProductRequest
type ProductUpdateProductRequest struct {

	// category ID
	CategoryID string `json:"categoryID,omitempty"`

	// description
	Description string `json:"description,omitempty"`

	// name
	Name string `json:"name,omitempty"`

	// price
	Price float64 `json:"price,omitempty"`

	// sku
	Sku string `json:"sku,omitempty"`

	// stock
	Stock uint64 `json:"stock,omitempty"`
}

// Validate validates this product update product request
func (m *ProductUpdateProductRequest) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this product update product request based on context it is used
func (m *ProductUpdateProductRequest) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *ProductUpdateProductRequest) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *ProductUpdateProductRequest) UnmarshalBinary(b []byte) error {
	var res ProductUpdateProductRequest
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
