// Code generated by go-swagger; DO NOT EDIT.

package api

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// SuccessfulAPIResponse successful Api response
//
// swagger:model SuccessfulApiResponse
type SuccessfulAPIResponse struct {

	// code
	Code int64 `json:"code,omitempty"`

	// a (key, value) map.
	Data interface{} `json:"data,omitempty"`

	// message
	Message string `json:"message,omitempty"`
}

// Validate validates this successful Api response
func (m *SuccessfulAPIResponse) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this successful Api response based on context it is used
func (m *SuccessfulAPIResponse) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *SuccessfulAPIResponse) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *SuccessfulAPIResponse) UnmarshalBinary(b []byte) error {
	var res SuccessfulAPIResponse
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
