// Code generated by go-swagger; DO NOT EDIT.

package api

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// UserCreateUserResponse user create user response
//
// swagger:model user.CreateUserResponse
type UserCreateUserResponse struct {

	// refresh token
	RefreshToken string `json:"refreshToken,omitempty"`

	// token
	Token string `json:"token,omitempty"`
}

// Validate validates this user create user response
func (m *UserCreateUserResponse) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this user create user response based on context it is used
func (m *UserCreateUserResponse) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *UserCreateUserResponse) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *UserCreateUserResponse) UnmarshalBinary(b []byte) error {
	var res UserCreateUserResponse
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
